#!/bin/sh

# Generates version.c
#
# Copyright (c) 1990 Chelsea Dyerman
# University of California, Berkeley (XCF)

if [ ! -f version.c ]
then
        generation=0
else
        generation=`sed -n 's/^const char \*generation = \"\(.*\)\";/\1/p' < version.c`
        if [ ! "$generation" ]; then generation=0; fi
fi

generation=`expr $generation + 1`
creation=`date | awk '{if (NF == 6) { print $1 " "  $2 " " $3 " "  $6 " at " $4 " " $5 } else { print $1 " "  $2 " " $3 " " $7 " at " $4 " " $5 " " $6 }}'`
cat > version.c <<EOF
/*
 * Copyright (c) 1990 Chelsea Dyerman
 * University of California, Berkeley (XCF)
 *
 * Some parts of this code -- in particular the dictionary based compression
 * code is Copyright 1995 by Dragon's Eye Productions
 *
 */

/*
 * This file is generated by mkversion.sh. Any changes made will go away.
 */

#include "patchlevel.h"
#include "params.h"
#include "interface.h"
#include "externs.h"

const char *generation = "$generation";
const char *creation = "$creation";
const char *version = PATCHLEVEL;

const char *infotext[] =
{

    RED VERSION WHITE " -- " AQUA GLOWVER,
    " ",
    WHITE
    "Based on the original code written by these programmers:",
    GREEN
    "  David Applegate    James Aspnes    Timothy Freeman    Bennet Yee",
    " ",
    WHITE
    "Others who have done major coding work along the way:",
    GREEN
    "  Lachesis, ChupChups, FireFoot, Russ 'Random' Smith, and Dr. Cat",
    " ",
    CYAN
    "This is a user-extendible, user-programmable multi-user adventure game.",
    CYAN
    "TinyMUCK was derived from TinyMUD v1.5.2, with extensive modifications.",
    CYAN
    "Because of all the modifications, this program is not in any way, shape,",
    CYAN
    "or form being supported by any of the original authors.  Any bugs, ideas,",
    CYAN
    "suggestions,  etc, should be directed to the persons listed below.",
    CYAN
    "Do not send diff files, send us mail about the bug and describe as best",
    CYAN
    "as you can, where you were at when the bug occured, and what you think",
    CYAN
    "caused the bug to be was produced, so we can try to reproduce it and",
    CYAN
    "track it down.",
    " ",
    WHITE
    "The following programmers currently maintain the code:",
    YELLOW
    "  PakRat/Artie:  artie@muq.org           GlowMuck Enhancements",
#ifdef PUEBLO
    YELLOW
    "  Loki/Jaybe:    jeremy@adobe.chaco.com  NeonPueblo Enhancements",
#endif
    YELLOW
    "  Foxen/Revar:   foxen@belfry.com        Main Fuzzball Developer",
    YELLOW
    "  Fre'ta:                                Crazy Fuzzball Developer",
    " ",
    WHITE
    "The following people helped out a lot along the way:",
    GREEN
    "  Fre'ta, Chris, Ermafelna, Lynx, WhiteFire, Kimi, Cynbe, Myk, Taldin,",
    GREEN
    "  Howard, darkfox, Moonchilde, Felorin, Xixia, Doran, Riss and King_Claudius.",
    " ",
    WHITE
    "Alpha and beta test sites, who put up with this nonsense:",
    PURPLE
    "  HighSeasMUCK, TygryssMUCK, FurryMUCK, CyberFurry, PendorMUCK, Kalasia,",
    PURPLE
    "  AnimeMUCK, Realms, FurryII, Tapestries, Unbridled Desires, TruffleMUCK,",
    PURPLE
    "  and Brazillian Dreams.",
    " ",
    WHITE
    "Places silly enough to give Foxen a wizbit at some time or another:",
    BLUE
    "  ChupMuck, HighSeas, TygMUCK, TygMUCK II, Furry, Pendor, Realms,",
    BLUE
    "  Kalasia, Anime, CrossRoadsMUCK, TestMage, MeadowFaire, TruffleMUCK,",
    BLUE
    "  Tapestries, Brazillian Dreams, SocioPolitical Ramifications, & more.",
    " ",
    YELLOW
    "Thanks also goes to those persons not mentioned here who have added",
    YELLOW
    "their advice, opinions, and code to TinyMUCK.",
    0,
};


void
do_credits(dbref player)
{
    int i;

    for (i = 0; infotext[i]; i++) {
        anotify(player, infotext[i]);
    }
}
EOF

exit 0
