
GlowMuck source code is Copyright 1996 by Andrew Nelson, all rights reserved.

There are no 2.0 versions of GlowMuck!  NeonMuck moved on to 2.X and thus I
was forced to rename my distributions and decided to call the server Glow. 
Neon code last used this code base as it's base around 1.5 or so.  See the
PAK_FIXES logfile in the Neon distribution for the exact version.

And now, Glow 3.0. (Hey if Microsoft can do it, why can't I? *smirk*)
Hmm, Glow 2001 ;)
